import { Command, Flags } from '@oclif/core';
import { execSync } from 'child_process';
import * as path from 'path';
import * as fs from 'fs-extra';
import chalk from 'chalk';
import ora from 'ora';
import { prompt } from 'enquirer';
import { getForgeDir } from '../config';

const SECRET_REGEXES = [
  /AKIA[0-9A-Z]{16}/, // AWS
  /ghp_[a-zA-Z0-9]{36}/, // GitHub
  /xox[baprs]-[0-9a-zA-Z]{10,48}/, // Slack
  /api[_-]?key[:=]\s*['"]?[a-zA-Z0-9]{20,}['"]?/i // Generic API Key
];

export default class Deploy extends Command {
  static description = 'Execute unified CI/CD deployment pipeline';

  async run(): Promise<void> {
    const targetDir = process.cwd();
    const forgeDir = getForgeDir(targetDir);
    const manifestPath = path.join(forgeDir, 'manifest.json');

    if (!(await fs.pathExists(manifestPath))) {
      this.error(chalk.red('Error: Project not initialized. Run "forge init" first.'));
    }

    const manifest = await fs.readJson(manifestPath);

    this.log(chalk.blue.bold('\n🚀 FORGE DEPLOYMENT PIPELINE'));
    this.log(chalk.dim('-----------------------------\n'));

    // 0. Branch Protection Check
    const currentBranch = execSync('git rev-parse --abbrev-ref HEAD').toString().trim();
    if (currentBranch === 'main' || currentBranch === 'master') {
      const { proceed } = await prompt<{ proceed: boolean }>({
        type: 'confirm',
        name: 'proceed',
        message: chalk.yellow(`Warning: You are on the ${chalk.bold(currentBranch)} branch. It is recommended to deploy from a feature branch. Proceed anyway?`),
        initial: false
      });
      if (!proceed) this.exit(0);
    }

    // 1. Pre-Flight Integrity
    await this.preFlightCheck();

    // 2. Handoff Gate
    const handoffData = await this.handoffGate();

    // 3. Generate Manifest
    const handoffSpinner = ora('Compiling Handoff Manifest...').start();
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const releaseDir = path.join(forgeDir, 'releases');
    await fs.ensureDir(releaseDir);
    
    const handoffPath = path.join(releaseDir, `HANDOFF_${timestamp}.md`);
    const handoffContent = `# RELEASE MANIFEST — ${manifest.name}

## 1. Business Viability
- **Objective**: ${handoffData.objective}
- **Architecture**: ${handoffData.architecture}
- **Cost Analysis**: ${handoffData.cost}

## 2. Technical Metadata
- **Project Format**: ${manifest.format}
- **Domain**: ${manifest.domain}
- **Version**: ${manifest.version}
- **Branch**: ${currentBranch}
- **Deployed At**: ${new Date().toISOString()}

---
*Generated by Forge CLI Deployment Pipeline*
`;
    await fs.writeFile(handoffPath, handoffContent, 'utf8');
    handoffSpinner.succeed(`Handoff Manifest archived: ${chalk.bold(`.forge/releases/HANDOFF_${timestamp}.md`)}`);

    // 4. Git Automation
    await this.gitAutomation(handoffPath, manifestPath, currentBranch);
  }

  private async preFlightCheck(): Promise<void> {
    const spinner = ora('Executing Pre-Flight Integrity Checks...').start();

    // A. Sync Check
    try {
      execSync('git fetch origin', { stdio: 'pipe' });
      const local = execSync('git rev-parse HEAD').toString().trim();
      const remote = execSync('git rev-parse @{u}').toString().trim();

      if (local !== remote) {
        spinner.fail(chalk.red('Sync Failure: Local branch is not synchronized with remote HEAD.'));
        this.exit(1);
      }
    } catch (e) {
      spinner.fail(chalk.red('Sync Failure: Could not verify branch synchronization.'));
      this.exit(1);
    }

    // B. Secret Scanning
    const scanSpinner = ora('Scanning for exposed secrets...').start();
    const files = execSync('git ls-files').toString().split('\n').filter(Boolean);
    
    for (const file of files) {
      if (file.includes('.forge/')) continue;
      try {
        const content = await fs.readFile(file, 'utf8');
        for (const regex of SECRET_REGEXES) {
          if (regex.test(content)) {
            scanSpinner.fail(chalk.red(`Security Vulnerability: Potential secret detected in ${chalk.bold(file)}`));
            this.exit(1);
          }
        }
      } catch (e) {
        // Skip binary files
      }
    }
    scanSpinner.succeed('Integrity verified. No vulnerabilities found.');
    spinner.succeed('Pre-flight complete.');
  }

  private async handoffGate(): Promise<{ objective: string; architecture: string; cost: string }> {
    this.log(chalk.yellow.bold('\n📝 THE HANDOFF GATE'));
    this.log(chalk.dim('Provide business viability data to proceed with deployment.\n'));

    return await prompt<{ objective: string; architecture: string; cost: string }>([
      { type: 'input', name: 'objective', message: 'Deployment Objective:', validate: (v: string) => v.length > 10 || 'Must be descriptive' },
      { type: 'input', name: 'architecture', message: 'Architecture Summary:', validate: (v: string) => v.length > 10 || 'Must be descriptive' },
      { type: 'input', name: 'cost', message: 'Cost Analysis / Resource Usage:', initial: 'Optimized for shared infrastructure' }
    ]);
  }

  private async gitAutomation(handoffPath: string, manifestPath: string, currentBranch: string): Promise<void> {
    const spinner = ora('Executing Handoff Automation...').start();

    try {
      // 1. Commit only the manifest and handoff files
      execSync(`git add "${handoffPath}" "${manifestPath}"`, { stdio: 'pipe' });
      execSync(`git commit -m "chore: release handoff manifest [${currentBranch}]" --no-verify`, { stdio: 'pipe' });
      
      // 2. Push
      execSync(`git push origin ${currentBranch}`, { stdio: 'pipe' });
      spinner.succeed('Manifest committed and pushed.');

      // 3. PR Creation (Attempt via gh CLI)
      const prSpinner = ora('Opening Pull Request...').start();
      try {
        const prExists = execSync(`gh pr list --head ${currentBranch} --json number --jq '.[0].number'`, { stdio: 'pipe' }).toString().trim();
        
        if (prExists && prExists !== '') {
          prSpinner.info(chalk.blue(`Pull Request #${prExists} already exists. Skipping creation.`));
        } else {
          execSync(`gh pr create --title "Release: ${path.basename(handoffPath)}" --body "Automated release handoff from Forge CLI." --base main`, { stdio: 'pipe' });
          prSpinner.succeed('Pull Request created successfully.');
        }
      } catch (e) {
        prSpinner.warn(chalk.yellow('Manual Action Required: GitHub CLI (gh) not found or PR failed. Please open a PR manually targeting the main branch.'));
      }

      this.log(chalk.green.bold('\n✅ DEPLOYMENT PIPELINE TRIGGERED'));
      this.log(chalk.white('The release workflow will now determine the build path based on your manifest.\n'));
    } catch (e) {
      spinner.fail(chalk.red('Automation failed. Please check git status and permissions.'));
      this.error(e as Error);
    }
  }
}
